version: '3'
services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails server -p 8080 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
volumes:
  db_data: {}
